spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://172.16.172.128:3306/users
#    username: users
#    password: 1234
    url: jdbc:mariadb://localhost:3306/users
    username: users
    password: 1234
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        format_sql: true
